tpmartin7/rideriot

- app/models/attempt.rb
- app/models/cycle_route.rb
- app/models/review.rb
- app/models/route_tag.rb
- app/models/tag.rb
- db/migrate/20210607143956_create_cycle_routes.rb
- db/migrate/20210607144551_create_tags.rb
- db/migrate/20210607145314_create_attempts.rb
- db/migrate/20210607145420_create_reviews.rb
- db/migrate/20210607145459_create_route_tags.rb
- db/migrate/20210607145748_add_distance_and_routes_to_users.rb
- db/migrate/20210607150729_add_name_to_users.rb
- db/schema.rb
- test/models/attempt_test.rb
- test/models/cycle_route_test.rb
- test/models/review_test.rb
- test/models/route_tag_test.rb
- test/models/tag_test.rb
> first migrations

- app/controllers/attempts_controller.rb
- app/controllers/cycle_routes_controller.rb
- app/controllers/reviews_controller.rb
- app/controllers/route_tags_controller.rb
- app/controllers/tags_controller.rb
- app/controllers/users_controller.rb
- test/controllers/attempts_controller_test.rb
- test/controllers/cycle_routes_controller_test.rb
- test/controllers/reviews_controller_test.rb
- test/controllers/route_tags_controller_test.rb
- test/controllers/tags_controller_test.rb
- test/controllers/users_controller_test.rb
> Added controllers

- Gemfile
- Gemfile.lock
- app/controllers/cycle_routes_controller.rb
- app/controllers/pages_controller.rb
- app/models/cycle_route.rb
- app/views/pages/home.html.erb
- config/initializers/geocoder.rb
- config/routes.rb
- db/migrate/20210607170715_add_coordinates_to_cycle_routes.rb
- db/schema.rb
added form on landing page that seaches cycle routes in the given location this will then filter the results and gives it to the cycle_routes show view
> Landing page search form

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/cycle_routes/index.html.erb
Added cycle_route/index page with basic cards to check we are feeding the routes through ok.
> Added cycle_route/index page 

- app/controllers/cycle_routes_controller.rb
- app/views/cycle_routes/show.html.erb
- config/routes.rb
created button on the cycle_routes show page that links to the attempt show page passing the cycle_route information
> Button feature

- .gitignore
- Gemfile.lock
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_global.scss
- app/controllers/cycle_routes_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
- config/routes.rb
first attempt at styling the users dashboard, still need to integrate has_friendship gem to create user friends and make a leaderboard of the total points they all have
> User dashboard

- app/assets/stylesheets/pages/_cycle_routes_index.scss
- app/controllers/attempts_controller.rb
- app/controllers/cycle_routes_controller.rb
- app/views/cycle_routes/index.html.erb
- app/views/cycle_routes/show.html.erb
- config/routes.rb
> 26 link pages

- app/controllers/cycle_routes_controller.rb
- app/controllers/pages_controller.rb
- app/views/cycle_routes/index.html.erb
- app/views/cycle_routes/show.html.erb
- app/views/pages/home.html.erb
Checkboxes on home page to pick tags. Tags are passed as params to index which only displays results with the tags specified. If no tags selected, show all results.
> Specify tags in search

- Gemfile.lock
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_modal.scss
- app/controllers/attempts_controller.rb
- app/views/attempts/show.html.erb
- app/views/layouts/application.html.erb
1. Removed navbar on attempt/show by adding remove method to attempts/controller
2. Added finish route button on attempt#show - triggers modal
3. Added modal with a summary of your route, CTA button to save points - needs to be linked up once destination page is ready
> Added buttons/modal to attempt show view

- app/assets/stylesheets/components/_card.scss
- app/views/cycle_routes/index.html.erb
- app/views/cycle_routes/show.html.erb
- db/migrate/20210610205138_add_map_image_to_cycle_routes.rb
- db/schema.rb
- db/seeds.rb
Improved the 4 initial seeds with static map overview images, descriptions, and distance in miles. Updated views to show the maps.
> 53 better seeds

- app/assets/stylesheets/components/_buttons.scss
- app/controllers/attempts_controller.rb
- app/views/attempts/show.html.erb
- app/views/reviews/new.html.erb
- config/routes.rb
added 3 working buttons on the attempts#show page modal after you click finish. They go to the correct routes, just need to create a reviews#create form
closes #55
> Attempt show page modal buttons now functional

- app/views/cycle_routes/show.html.erb
changed the div width of the star rating on the show page so it doesn't bunch up
> show page styling

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_modal.scss
- app/views/attempts/show.html.erb
- app/views/cycle_routes/show.html.erb
- app/views/reviews/new.html.erb
- app/views/users/show.html.erb
Altered the naming convention in some CSS to be less general
> CSS name change

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_modal.scss
- app/views/attempts/show.html.erb
- app/views/cycle_routes/show.html.erb
- app/views/reviews/new.html.erb
- app/views/users/show.html.erb
Removed purple card border, 
Fixed spacing on buttons on a few buttons
> Styling changes - 

- Gemfile.lock
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_reviews.scss
- app/views/reviews/new.html.erb
Cleaned up the review#view styling
Fixed button and positioning
> Review styling view

- app/assets/stylesheets/components/_tag.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- db/seeds.rb
> Landing page styled

- app/assets/stylesheets/components/_tag.scss
- app/views/cycle_routes/index.html.erb
> Removed tags label. Tag colors match pills on landing page.

- app/controllers/attempts_controller.rb
- app/views/attempts/show.html.erb
(as minutes for demo purposes)
> Seconds to complete route now display correctly 

- app/assets/stylesheets/components/_card.scss
- app/controllers/cycle_routes_controller.rb
- app/views/cycle_routes/index.html.erb
- app/views/cycle_routes/show.html.erb
- db/seeds.rb
made titles more descriptive in seeds
> Moved title to top of cards, changed stars to gold

- config/meta.yml
Added new absolute url image to the meta.yml
> Checklist tweaks
